n = 50 # number of nodes
z0 = 0.5 # fraction of slow nodes
z1 = 0.5 # fraction of low cpu nodes
inter_txn_time = 10 # inter transaction time
c_slow = 5 # link speed for slow internet (in Kbpms)
c_fast = 100 # link spped for fast internet (in Kbmps)
rho_lb = 10 # propagation delay lower bound (in ms)
rho_ub = 500 # propagation delay upper bound (in ms)
queuing_delay_constant = 96 # (in kbits)
SIZE_TXN = 8 # in Kb
SIZE_BLK = 8*1024 # in Kb 
GENERATE_TXN = 0
RECEIVE_TXN = 1
GENERATE_BLK = 2
RECEIVE_BLK = 3